import { useState, useRef } from 'react';
import { useResumeContext } from '../../context/ResumeContext';
import './FileUploader.css';

function FileUploader() {
  const { setMasterResume, isLoading, setIsLoading } = useResumeContext();
  const [isDragActive, setIsDragActive] = useState(false);
  const [fileName, setFileName] = useState('');
  const fileInputRef = useRef(null);

  const handleDragOver = (e) => {
    e.preventDefault();
    setIsDragActive(true);
  };

  const handleDragLeave = () => {
    setIsDragActive(false);
  };

  const processFile = async (file) => {
    if (!file) return;
    
    // Accept only PDF or DOCX
    if (file.type !== 'application/pdf' && !file.name.endsWith('.docx')) {
      alert('Please upload a PDF or DOCX file.');
      return;
    }

    setFileName(file.name);
    setIsLoading(true);

    try {
      // 1. Prepare the file as FormData
      const formData = new FormData();
      formData.append('resume', file); // 'resume' matches upload.single('resume') in backend

      // 2. Send to Node.js backend
      const response = await fetch('http://localhost:5000/api/resume/upload-master', {
        method: 'POST',
        body: formData, // No Content-Type header needed; fetch sets it automatically for FormData
      });

      if (!response.ok) {
        throw new Error(`Server responded with status: ${response.status}`);
      }

      // 3. Receive the structured JSON generated by Gemini
      const data = await response.json();
      
      // 4. Save to Global Context
      setMasterResume(data);
      
    } catch (error) {
      console.error("Error parsing file:", error);
      alert("Failed to parse resume. Make sure your Node.js backend is running!");
      setFileName(''); // Reset UI on failure
    } finally {
      setIsLoading(false);
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragActive(false);
    const file = e.dataTransfer.files[0];
    processFile(file);
  };

  const handleChange = (e) => {
    const file = e.target.files[0];
    processFile(file);
  };

  return (
    <div 
      className={`uploader-container ${isDragActive ? 'drag-active' : ''}`}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
      onClick={() => fileInputRef.current.click()}
    >
      <input 
        type="file" 
        ref={fileInputRef} 
        onChange={handleChange} 
        className="file-input"
        accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      />
      
      <div className="uploader-icon">📄</div>
      
      {isLoading ? (
        <p className="uploader-text">Extracting structure via Gemini AI...</p>
      ) : fileName ? (
        <div className="success-message">
          <span>✅</span> {fileName} uploaded and parsed successfully!
        </div>
      ) : (
        <>
          <p className="uploader-text">Drag & drop your Master Resume here</p>
          <p className="uploader-subtext">Supports PDF and DOCX files up to 5MB</p>
        </>
      )}
    </div>
  );
}

export default FileUploader;